# Encoding: utf-8

# --
# Copyright (c) 2008-2018 Net-ng.
# All rights reserved.
#
# This software is licensed under the BSD License, as described in
# the file LICENSE.txt, which you should have received as part of
# this distribution.
# --

image: docker-registry.net-ng.com/nng/dind-ubuntu:7

tests2:
  script:
    - pip2 install flake8 pytest .
    - flake8 nagare
    - pytest

tests3:
  script:
  - pip3 install flake8 pytest .
  - flake8 nagare
  - pytest
